trigger:
- deploy/vps

pool:
  name: 'Camai-Agent'

variables:
- group: web-admin-group
- group: docker

steps:
- task: Docker@2
  displayName: 'Docker build and publish'
  inputs:
    containerRegistry: 'camai-hub'
    repository: 'milease/camai-backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: './'
    tags: 'camai-web-admin'
- script: |
    echo "VITE_SERVER_LINK=$(VITE_SERVER_LINK)" > .env
  displayName: 'Write .env'
  
- task: CopyFilesOverSSH@0
  displayName: 'Copy files'
  inputs:
    sshEndpoint: 'ssh-server'
    contents: |
      .env
      ./Deploy/docker-compose.yml
    targetFolder: 'frontend/admin'
    readyTimeout: '20000'

- task: SSH@0
  displayName: 'Pull and run image'
  inputs:
    sshEndpoint: 'ssh-server'
    runOptions: 'inline'
    inline: |
      cd frontend/admin
      mv Deploy/*yml .
      rmdir Deploy
      echo $(docker.password) | docker login -u $(docker.username) --password-stdin 2>&1
      docker compose down web 2>&1
      docker rmi milease/camai-backend:camai-web-admin 2>&1
      docker compose up -d --quiet-pull 2>&1
    readyTimeout: '20000'
